# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EMInterwovenFastICA <- function(DataMtr, MembershipProbs_, bandWidth, maxIteration = 300L, icaIteration = 150L, tolerance = 1e-6, verbose = TRUE, combine = TRUE) {
    .Call(icamix_EMInterwovenFastICA, DataMtr, MembershipProbs_, bandWidth, maxIteration, icaIteration, tolerance, verbose, combine)
}

WtsFastICA <- function(X, wts, Wconst, verbose = TRUE, alpha = 1, maxIteration = 60L, tolerance = 1e-6) {
    .Call(icamix_WtsFastICA, X, wts, Wconst, verbose, alpha, maxIteration, tolerance)
}

WtsKde <- function(X, wts, grid, h) {
    .Call(icamix_WtsKde, X, wts, grid, h)
}

